# Generated by Django 4.2.13 on 2026-03-24 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_analysishistory_recommended_cafe_type'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='analysishistory',
            new_name='analysis_hi_user_id_3c1bf9_idx',
            old_name='analysis_his_user_id_68efc2_idx',
        ),
    ]
